version: "3.8"

services:
  parkship:
    container_name: parkship
    restart: always
    build: "."
    depends_on:
      - postgres
    environment:
      - PARKSHIP_ENV=${PARKSHIP_ENV}
      - JDBC_DATABASE_URL=${JDBC_DATABASE_URL}
      - JDBC_DATABASE_USERNAME=${JDBC_DATABASE_USERNAME}
      - JDBC_DATABASE_PASSWORD=${JDBC_DATABASE_PASSWORD}
    ports:
      - "80:80"
      
  postgres:
    container_name: postgres
    image: postgres:latest
    # macos: platform: linux/amd64
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=parkshipdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data
