name: Build Push Deploy Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildpush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend with Maven
        working-directory: ./backend
        run: mvn clean install

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      - name: Install npm packages
        working-directory: ./frontend
        run: npm install
      - name: Run tests
        working-directory: ./frontend
        run: npm test --if-present
      - name: Build nextjs application
        working-directory: ./frontend
        run: npm run build --if-present

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2       

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v4
        name: Build image and push to dockerhub
        with:
            context: .
            push: true
            tags: edelmetall/parkship:${{ github.sha }}
            file: ./Dockerfile
            
  deploy:
      runs-on: ubuntu-latest
      needs: buildpush
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'parkship-app'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_6e30f50bc3df43d4a15607742c52585f }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b88fc97a3b844ab4ac8937bbfe4fe249 }}/parkship:${{ github.sha }}'