name: Backend CI

on:
  push:
    branches:
        - '*'
        - '!main'
  pull_request:
    branches: ["staging"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build backend with Maven
        working-directory: ./backend
        run: mvn clean install

      - name: Run tests
        working-directory: ./backend
        run: mvn test