# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Backend CI flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Backend with Maven
      working-directory: ./backend
      run: mvn clean install

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push backend Docker image
      with:
          image: edelmetall/parkship-backend
          tags: latest
          registry: docker.io
          dockerfile: ./backend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --tag edelmetall/parkship-frontend:latest && docker push edelmetall/parkship-frontend:latest 
